
[general]
	#Soft cap on how many tubes can exist in a contiguous network of tubes. Items are transported slowlier in networks of greater size than this value, sigifying to the player that they have too many tubes.
	#Range: 1 ~ 10000
	soft_tube_cap = 400
	#Hard cap on how many tubes can exist in a contiguous network of tubes. If a player attempts to make a network of greater size from this value, not all tubes in the attempted network will become part of that network.
	#Range: 1 ~ 10000
	hard_tube_cap = 500
	#Base time in ticks that a moving itemstack spends in each individual tube block. Adjusted by other factors.
	#Range: 1 ~ 72000
	ticks_in_tube = 10
	#Max items that can fit in a single tube. A tube block will break if the number of itemstacks contained with them is greater than this value, dropping their items on the ground
	#Range: > 1
	max_items_in_tube = 2147483647
	#Osmosis filter automatic item transfer rate in ticks per item. The default value of 8 is the same as vanilla hoppers.
	#Range: > 1
	osmosis_filter_transfer_rate = 8
	#Maximum range at which tubes can be remotely connected to each other. This also affects how many nearby chunks are checked for longtube intersections when placing a block.
	#Range: 0.0 ~ 1.7976931348623157E308
	max_remote_tube_connection_range = 16.0

